### **1. Створити двомірний нульовий масив розміром 11х11 та заповнити його діагоналі одиницями.**

```
# Выбран кодовый формат
```



In [ ]:
import numpy as np
import cv2

In [ ]:
array = np.zeros((11,11))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
for i in range(11):
	for j in range(11):
		if (i==j):
			array[i][j] = 1
		elif ( i+j ==10):
			array[i][j] = 1

In [ ]:
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


## **2. Засобами NumPy створити вертикальні та горизонтальні зображення градієнту в обидва боки (поступове збільшення яскравості на зображенні).**

In [ ]:
horiz_grad = np.zeros((255,255))

In [ ]:
w = horiz_grad.shape[1]
h = horiz_grad.shape[0]

print(w)
print(h)

255
255


In [ ]:
for i in range(w):
    for j in range(h):
        horiz_grad[j][i] = horiz_grad[j][i] + j

print(horiz_grad)

[[  0.   1.   2. ... 252. 253. 254.]
 [  1.   1.   2. ... 252. 253. 254.]
 [  2.   3.   2. ... 252. 253. 254.]
 ...
 [252. 253. 254. ... 252. 253. 254.]
 [253. 254. 255. ... 505. 253. 254.]
 [254. 255. 256. ... 506. 507. 254.]]


In [ ]:
cv2.imwrite('horiz_grad.jpg', horiz_grad)

True

 **2.5 Аналогічно створити горизонтальний градієнт в інший бік**

In [ ]:
horiz_grad_reverse = np.full((255,255), 255)

w = horiz_grad_reverse.shape[1]
h = horiz_grad_reverse.shape[0]
for i in range(w):
    for j in range(h):
        horiz_grad_reverse[j][i] = horiz_grad_reverse[j][i] - j

In [ ]:
cv2.imwrite('horiz_grad_reverse.jpg', horiz_grad_reverse)

True

# **Вертикальний градієнт**

In [ ]:
vert_grad = np.zeros((255,255))

w = vert_grad.shape[1]
h = vert_grad.shape[0]
for i in range(w):
    for j in range(h):
        vert_grad[i][j] = vert_grad[i][j] + j

In [ ]:
cv2.imwrite('vert_grad.jpg', vert_grad)

True

**Вертикальний градієнт reverse**

In [ ]:
vert_grad_reverse = np.full((255,255),255)

w = vert_grad_reverse.shape[1]
h = vert_grad_reverse.shape[0]
for i in range(w):
    for j in range(h):
        vert_grad_reverse[i][j] = vert_grad_reverse[i][j] - j

In [ ]:
cv2.imwrite('vert_grad_reverse.jpg', vert_grad_reverse)

True